#!/usr/bin/env ruby

BACKUP_DIR = File.expand_path("./backups")
$backups_taken = 0

def backup_path(path)
  candidate = File.expand_path(path)
  index = 1
  while File.exist?(candidate)
    candidate = "#{path}.#{index}"
    index += 1
  end
  candidate
end

def backup_previous_version_of(link)
  return unless File.exist?(link)
  %x[mkdir -p #{BACKUP_DIR}] unless File.directory?(BACKUP_DIR)
  backup = backup_path(BACKUP_DIR + '/' + File.basename(link))
  %x[cp -R -H #{link} #{backup}]
  %x[rm -r #{link}]
  $backups_taken += 1 
end

Dir.glob("./.*").push(Dir.glob("./*")).flatten.each do |f|
  filename = File.basename(f)
  next if filename =~ /^\.\.?$/
  next if filename == ".git"
  next if filename == File.basename(__FILE__)
  next if filename == File.basename(BACKUP_DIR)
  link_target = File.expand_path(f)
  link = File.expand_path("~/#{filename}")
  backup_previous_version_of(link)
  %x[ln -s #{link_target} #{link}]
end

puts "Backups of old dotfiles can be found in #{BACKUP_DIR}" if $backups_taken > 0
